-- Production-like local state is intentional. The company registry is created
-- by migrations, while test members are inserted inside rollback-only pgTAP
-- transactions. SwiftUI previews use MockBackendService and never need rows in
-- the local database.
