-- Conservative V1 launch registry: established technology companies with
-- well-known corporate email domains. Additions remain an operational review.
insert into public.company_domains (domain, company_name, industry, status)
values
  ('apple.com', 'Apple', 'Consumer technology and platforms', 'approved'),
  ('google.com', 'Google', 'Internet products and cloud technology', 'approved'),
  ('microsoft.com', 'Microsoft', 'Software and cloud technology', 'approved'),
  ('amazon.com', 'Amazon', 'Commerce and cloud technology', 'approved'),
  ('meta.com', 'Meta', 'Consumer technology', 'approved'),
  ('netflix.com', 'Netflix', 'Streaming technology', 'approved'),
  ('nvidia.com', 'NVIDIA', 'Accelerated computing', 'approved'),
  ('openai.com', 'OpenAI', 'Artificial intelligence', 'approved'),
  ('anthropic.com', 'Anthropic', 'Artificial intelligence', 'approved'),
  ('shopify.com', 'Shopify', 'Commerce technology', 'approved'),
  ('stripe.com', 'Stripe', 'Financial infrastructure', 'approved'),
  ('uber.com', 'Uber', 'Mobility technology', 'approved'),
  ('airbnb.com', 'Airbnb', 'Travel technology', 'approved'),
  ('cloudflare.com', 'Cloudflare', 'Internet infrastructure', 'approved'),
  ('datadoghq.com', 'Datadog', 'Cloud monitoring', 'approved'),
  ('snowflake.com', 'Snowflake', 'Cloud data platforms', 'approved'),
  ('mongodb.com', 'MongoDB', 'Developer data platforms', 'approved'),
  ('github.com', 'GitHub', 'Developer platforms', 'approved'),
  ('linkedin.com', 'LinkedIn', 'Professional technology', 'approved'),
  ('salesforce.com', 'Salesforce', 'Enterprise software', 'approved'),
  ('adobe.com', 'Adobe', 'Creative and document technology', 'approved'),
  ('slack.com', 'Slack', 'Workplace collaboration', 'approved'),
  ('twilio.com', 'Twilio', 'Communications infrastructure', 'approved'),
  ('coinbase.com', 'Coinbase', 'Financial technology', 'approved'),
  ('figma.com', 'Figma', 'Collaborative design technology', 'approved'),
  ('atlassian.com', 'Atlassian', 'Developer and collaboration tools', 'approved'),
  ('dropbox.com', 'Dropbox', 'Cloud collaboration', 'approved'),
  ('doordash.com', 'DoorDash', 'Local commerce technology', 'approved'),
  ('lyft.com', 'Lyft', 'Mobility technology', 'approved'),
  ('pinterest.com', 'Pinterest', 'Consumer technology', 'approved'),
  ('snap.com', 'Snap', 'Consumer technology', 'approved'),
  ('intel.com', 'Intel', 'Semiconductor technology', 'approved'),
  ('amd.com', 'AMD', 'Semiconductor technology', 'approved'),
  ('ibm.com', 'IBM', 'Enterprise technology', 'approved'),
  ('oracle.com', 'Oracle', 'Enterprise software and cloud technology', 'approved'),
  ('wealthsimple.com', 'Wealthsimple', 'Financial technology', 'approved'),
  ('1password.com', '1Password', 'Security technology', 'approved'),
  ('clio.com', 'Clio', 'Legal technology', 'approved'),
  ('cohere.com', 'Cohere', 'Artificial intelligence', 'approved'),
  ('thomsonreuters.com', 'Thomson Reuters', 'Information technology', 'approved')
on conflict (domain) do update set
  company_name = excluded.company_name,
  industry = excluded.industry,
  status = excluded.status;

