-- Company registry (feature 002, verified company marks).
-- The registry becomes one row per company (public.companies) with one or more work-email
-- domains (public.company_domains). Sign-up eligibility still reads company_domains.status;
-- company marks (next migration) read companies.status. Expands the launch registry to
-- 249 well-known North American technology companies and employers, each recorded with
-- the coverage clause that admitted it (a: index constituent or its subsidiary, b: private with
-- at least 1,000 employees, c: at least 200 engineering staff in Toronto, launch: carried over
-- from the initial registry). Re-runnable. No operator step.

create table if not exists public.companies (
  key text primary key check (key ~ '^[a-z0-9][a-z0-9-]{0,62}$'),
  name text not null check (char_length(name) between 1 and 120),
  industry text not null check (char_length(industry) between 1 and 120),
  website_url text check (website_url is null or (website_url ~ '^https://' and char_length(website_url) <= 200)),
  coverage_clause text not null check (coverage_clause in ('a', 'b', 'c', 'launch')),
  status text not null default 'approved' check (status in ('approved', 'review_pending', 'rejected')),
  mark_status text not null default 'not_yet_fetched'
    check (mark_status in ('not_yet_fetched', 'available', 'no_icon_published', 'fetch_failed', 'withheld')),
  mark_version integer not null default 0 check (mark_version >= 0),
  mark_path text check (mark_path is null or mark_path ~ '^[a-z0-9][a-z0-9-]{0,62}/[0-9]+\.(png|jpg)$'),
  mark_content_type text check (mark_content_type is null or mark_content_type in ('image/png', 'image/jpeg')),
  mark_fetched_at timestamptz,
  mark_source_url text check (mark_source_url is null or char_length(mark_source_url) <= 500),
  mark_failure_reason text check (mark_failure_reason is null or char_length(mark_failure_reason) <= 300),
  mark_refresh_requested boolean not null default false,
  mark_claimed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.companies enable row level security;
revoke all on table public.companies from public, anon, authenticated;

drop trigger if exists companies_touch on public.companies;
create trigger companies_touch before update on public.companies
for each row execute function private.touch_updated_at();

alter table public.company_domains
  add column if not exists company_key text references public.companies(key);

create index if not exists company_domains_company_key_idx on public.company_domains(company_key);

-- One company, one displayed name: the domain row mirrors its company so the sign-up trigger
-- and validate_company_domain keep reading company_domains exactly as before.
create or replace function private.sync_company_domain_names()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare derived_key text;
begin
  if tg_table_name = 'companies' then
    update public.company_domains d
      set company_name = new.name, industry = new.industry
      where d.company_key = new.key
        and (d.company_name is distinct from new.name or d.industry is distinct from new.industry);
    return new;
  end if;

  -- A domain inserted without a company (older tooling, manual SQL) becomes its own company
  -- so the registry invariant "every domain belongs to one company" always holds.
  if new.company_key is null then
    derived_key := trim(both '-' from regexp_replace(lower(coalesce(new.company_name, '')), '[^a-z0-9]+', '-', 'g'));
    if derived_key = '' or derived_key !~ '^[a-z0-9][a-z0-9-]{0,62}$' then
      derived_key := trim(both '-' from regexp_replace(lower(new.domain), '[^a-z0-9]+', '-', 'g'));
    end if;
    insert into public.companies (key, name, industry, website_url, coverage_clause, status)
    values (derived_key, new.company_name, new.industry, 'https://' || new.domain, 'launch', new.status)
    on conflict (key) do nothing;
    new.company_key := derived_key;
  end if;

  select c.name, c.industry into new.company_name, new.industry
  from public.companies c
  where c.key = new.company_key;
  return new;
end;
$$;

revoke all on function private.sync_company_domain_names() from public, anon, authenticated, service_role;

drop trigger if exists companies_sync_domain_names on public.companies;
create trigger companies_sync_domain_names after insert or update of name, industry on public.companies
for each row execute function private.sync_company_domain_names();

drop trigger if exists company_domains_sync_names on public.company_domains;
create trigger company_domains_sync_names before insert or update of company_key on public.company_domains
for each row execute function private.sync_company_domain_names();

-- Launch registry carried over (clause recorded per company).
insert into public.companies (key, name, industry, website_url, coverage_clause, status)
values
  ('apple', 'Apple', 'Consumer technology and platforms', 'https://apple.com', 'a', 'approved'),
  ('google', 'Google', 'Internet products and cloud technology', 'https://google.com', 'a', 'approved'),
  ('microsoft', 'Microsoft', 'Software and cloud technology', 'https://microsoft.com', 'a', 'approved'),
  ('amazon', 'Amazon', 'Commerce and cloud technology', 'https://amazon.com', 'a', 'approved'),
  ('meta', 'Meta', 'Consumer technology', 'https://meta.com', 'a', 'approved'),
  ('netflix', 'Netflix', 'Streaming technology', 'https://netflix.com', 'a', 'approved'),
  ('nvidia', 'NVIDIA', 'Accelerated computing', 'https://nvidia.com', 'a', 'approved'),
  ('openai', 'OpenAI', 'Artificial intelligence', 'https://openai.com', 'b', 'approved'),
  ('anthropic', 'Anthropic', 'Artificial intelligence', 'https://anthropic.com', 'b', 'approved'),
  ('shopify', 'Shopify', 'Commerce technology', 'https://shopify.com', 'a', 'approved'),
  ('stripe', 'Stripe', 'Financial infrastructure', 'https://stripe.com', 'b', 'approved'),
  ('uber', 'Uber', 'Mobility technology', 'https://uber.com', 'a', 'approved'),
  ('airbnb', 'Airbnb', 'Travel technology', 'https://airbnb.com', 'a', 'approved'),
  ('cloudflare', 'Cloudflare', 'Internet infrastructure', 'https://cloudflare.com', 'a', 'approved'),
  ('datadog', 'Datadog', 'Cloud monitoring', 'https://datadoghq.com', 'a', 'approved'),
  ('snowflake', 'Snowflake', 'Cloud data platforms', 'https://snowflake.com', 'a', 'approved'),
  ('mongodb', 'MongoDB', 'Developer data platforms', 'https://mongodb.com', 'a', 'approved'),
  ('github', 'GitHub', 'Developer platforms', 'https://github.com', 'a', 'approved'),
  ('linkedin', 'LinkedIn', 'Professional technology', 'https://linkedin.com', 'a', 'approved'),
  ('salesforce', 'Salesforce', 'Enterprise software', 'https://salesforce.com', 'a', 'approved'),
  ('adobe', 'Adobe', 'Creative and document technology', 'https://adobe.com', 'a', 'approved'),
  ('slack', 'Slack', 'Workplace collaboration', 'https://slack.com', 'a', 'approved'),
  ('twilio', 'Twilio', 'Communications infrastructure', 'https://twilio.com', 'launch', 'approved'),
  ('coinbase', 'Coinbase', 'Financial technology', 'https://coinbase.com', 'a', 'approved'),
  ('figma', 'Figma', 'Collaborative design technology', 'https://figma.com', 'launch', 'approved'),
  ('atlassian', 'Atlassian', 'Developer and collaboration tools', 'https://atlassian.com', 'a', 'approved'),
  ('dropbox', 'Dropbox', 'Cloud collaboration', 'https://dropbox.com', 'launch', 'approved'),
  ('doordash', 'DoorDash', 'Local commerce technology', 'https://doordash.com', 'a', 'approved'),
  ('lyft', 'Lyft', 'Mobility technology', 'https://lyft.com', 'launch', 'approved'),
  ('pinterest', 'Pinterest', 'Consumer technology', 'https://pinterest.com', 'launch', 'approved'),
  ('snap', 'Snap', 'Consumer technology', 'https://snap.com', 'launch', 'approved'),
  ('intel', 'Intel', 'Semiconductor technology', 'https://intel.com', 'a', 'approved'),
  ('amd', 'AMD', 'Semiconductor technology', 'https://amd.com', 'a', 'approved'),
  ('ibm', 'IBM', 'Enterprise technology', 'https://ibm.com', 'a', 'approved'),
  ('oracle', 'Oracle', 'Enterprise software and cloud technology', 'https://oracle.com', 'a', 'approved'),
  ('wealthsimple', 'Wealthsimple', 'Financial technology', 'https://wealthsimple.com', 'b', 'approved'),
  ('1password', '1Password', 'Security technology', 'https://1password.com', 'b', 'approved'),
  ('clio', 'Clio', 'Legal technology', 'https://clio.com', 'b', 'approved'),
  ('cohere', 'Cohere', 'Artificial intelligence', 'https://cohere.com', 'c', 'approved'),
  ('thomson-reuters', 'Thomson Reuters', 'Information technology', 'https://thomsonreuters.com', 'a', 'approved')
on conflict (key) do update set
  name = excluded.name,
  industry = excluded.industry,
  website_url = coalesce(public.companies.website_url, excluded.website_url),
  coverage_clause = excluded.coverage_clause;

insert into public.company_domains (domain, company_key, company_name, industry, status)
values
  ('apple.com', 'apple', 'Apple', 'Consumer technology and platforms', 'approved'),
  ('google.com', 'google', 'Google', 'Internet products and cloud technology', 'approved'),
  ('microsoft.com', 'microsoft', 'Microsoft', 'Software and cloud technology', 'approved'),
  ('amazon.com', 'amazon', 'Amazon', 'Commerce and cloud technology', 'approved'),
  ('meta.com', 'meta', 'Meta', 'Consumer technology', 'approved'),
  ('netflix.com', 'netflix', 'Netflix', 'Streaming technology', 'approved'),
  ('nvidia.com', 'nvidia', 'NVIDIA', 'Accelerated computing', 'approved'),
  ('openai.com', 'openai', 'OpenAI', 'Artificial intelligence', 'approved'),
  ('anthropic.com', 'anthropic', 'Anthropic', 'Artificial intelligence', 'approved'),
  ('shopify.com', 'shopify', 'Shopify', 'Commerce technology', 'approved'),
  ('stripe.com', 'stripe', 'Stripe', 'Financial infrastructure', 'approved'),
  ('uber.com', 'uber', 'Uber', 'Mobility technology', 'approved'),
  ('airbnb.com', 'airbnb', 'Airbnb', 'Travel technology', 'approved'),
  ('cloudflare.com', 'cloudflare', 'Cloudflare', 'Internet infrastructure', 'approved'),
  ('datadoghq.com', 'datadog', 'Datadog', 'Cloud monitoring', 'approved'),
  ('snowflake.com', 'snowflake', 'Snowflake', 'Cloud data platforms', 'approved'),
  ('mongodb.com', 'mongodb', 'MongoDB', 'Developer data platforms', 'approved'),
  ('github.com', 'github', 'GitHub', 'Developer platforms', 'approved'),
  ('linkedin.com', 'linkedin', 'LinkedIn', 'Professional technology', 'approved'),
  ('salesforce.com', 'salesforce', 'Salesforce', 'Enterprise software', 'approved'),
  ('adobe.com', 'adobe', 'Adobe', 'Creative and document technology', 'approved'),
  ('slack.com', 'slack', 'Slack', 'Workplace collaboration', 'approved'),
  ('twilio.com', 'twilio', 'Twilio', 'Communications infrastructure', 'approved'),
  ('coinbase.com', 'coinbase', 'Coinbase', 'Financial technology', 'approved'),
  ('figma.com', 'figma', 'Figma', 'Collaborative design technology', 'approved'),
  ('atlassian.com', 'atlassian', 'Atlassian', 'Developer and collaboration tools', 'approved'),
  ('dropbox.com', 'dropbox', 'Dropbox', 'Cloud collaboration', 'approved'),
  ('doordash.com', 'doordash', 'DoorDash', 'Local commerce technology', 'approved'),
  ('lyft.com', 'lyft', 'Lyft', 'Mobility technology', 'approved'),
  ('pinterest.com', 'pinterest', 'Pinterest', 'Consumer technology', 'approved'),
  ('snap.com', 'snap', 'Snap', 'Consumer technology', 'approved'),
  ('intel.com', 'intel', 'Intel', 'Semiconductor technology', 'approved'),
  ('amd.com', 'amd', 'AMD', 'Semiconductor technology', 'approved'),
  ('ibm.com', 'ibm', 'IBM', 'Enterprise technology', 'approved'),
  ('ca.ibm.com', 'ibm', 'IBM', 'Enterprise technology', 'approved'),
  ('oracle.com', 'oracle', 'Oracle', 'Enterprise software and cloud technology', 'approved'),
  ('wealthsimple.com', 'wealthsimple', 'Wealthsimple', 'Financial technology', 'approved'),
  ('1password.com', '1password', '1Password', 'Security technology', 'approved'),
  ('clio.com', 'clio', 'Clio', 'Legal technology', 'approved'),
  ('cohere.com', 'cohere', 'Cohere', 'Artificial intelligence', 'approved'),
  ('thomsonreuters.com', 'thomson-reuters', 'Thomson Reuters', 'Information technology', 'approved'),
  ('tr.com', 'thomson-reuters', 'Thomson Reuters', 'Information technology', 'approved')
on conflict (domain) do update set company_key = excluded.company_key;

-- Any domain added outside a migration before this one becomes its own company.
do $$
declare row_record record; derived_key text;
begin
  for row_record in
    select d.domain, d.company_name, d.industry, d.status
    from public.company_domains d
    where d.company_key is null
  loop
    derived_key := trim(both '-' from regexp_replace(lower(row_record.company_name), '[^a-z0-9]+', '-', 'g'));
    if derived_key = '' or derived_key !~ '^[a-z0-9][a-z0-9-]{0,62}$' then
      derived_key := trim(both '-' from regexp_replace(lower(row_record.domain), '[^a-z0-9]+', '-', 'g'));
    end if;
    insert into public.companies (key, name, industry, website_url, coverage_clause, status)
    values (derived_key, row_record.company_name, row_record.industry, 'https://' || row_record.domain, 'launch', row_record.status)
    on conflict (key) do nothing;
    update public.company_domains set company_key = derived_key where domain = row_record.domain;
  end loop;
end;
$$;

alter table public.company_domains alter column company_key set not null;

-- Registry expansion: 209 companies.
insert into public.companies (key, name, industry, website_url, coverage_clause, status)
values
  ('activision-blizzard', 'Activision Blizzard', 'Gaming technology', 'https://www.activisionblizzard.com', 'a', 'approved'),
  ('adp', 'ADP', 'HR technology', 'https://www.adp.com', 'a', 'approved'),
  ('affirm', 'Affirm', 'Financial technology', 'https://www.affirm.com', 'c', 'approved'),
  ('akamai', 'Akamai', 'Internet infrastructure', 'https://akamai.com', 'a', 'approved'),
  ('alteryx', 'Alteryx', 'Analytics software', 'https://www.alteryx.com', 'b', 'approved'),
  ('analog-devices', 'Analog Devices', 'Semiconductor technology', 'https://analog.com', 'a', 'approved'),
  ('anaplan', 'Anaplan', 'Planning software', 'https://www.anaplan.com', 'b', 'approved'),
  ('anduril', 'Anduril', 'Defense technology', 'https://anduril.com', 'b', 'approved'),
  ('ansys', 'Ansys', 'Simulation software', 'https://www.ansys.com', 'a', 'approved'),
  ('applied-intuition', 'Applied Intuition', 'Mobility technology', 'https://appliedintuition.com', 'b', 'approved'),
  ('applied-materials', 'Applied Materials', 'Semiconductor equipment', 'https://amat.com', 'a', 'approved'),
  ('applovin', 'AppLovin', 'Mobile advertising technology', 'https://applovin.com', 'a', 'approved'),
  ('arctic-wolf', 'Arctic Wolf', 'Security technology', 'https://arcticwolf.com', 'b', 'approved'),
  ('arista', 'Arista', 'Networking technology', 'https://arista.com', 'a', 'approved'),
  ('assent', 'Assent', 'Supply chain compliance software', 'https://assent.com', 'b', 'approved'),
  ('athenahealth', 'athenahealth', 'Health technology', 'https://www.athenahealth.com', 'b', 'approved'),
  ('autodesk', 'Autodesk', 'Design software', 'https://autodesk.com', 'a', 'approved'),
  ('automation-anywhere', 'Automation Anywhere', 'Automation software', 'https://www.automationanywhere.com', 'b', 'approved'),
  ('automattic', 'Automattic', 'Web publishing technology', 'https://automattic.com', 'b', 'approved'),
  ('avalara', 'Avalara', 'Tax technology', 'https://www.avalara.com', 'b', 'approved'),
  ('axon', 'Axon', 'Public safety technology', 'https://axon.com', 'a', 'approved'),
  ('bamboohr', 'BambooHR', 'HR technology', 'https://www.bamboohr.com', 'b', 'approved'),
  ('barracuda', 'Barracuda Networks', 'Security technology', 'https://www.barracuda.com', 'b', 'approved'),
  ('behaviour-interactive', 'Behaviour Interactive', 'Gaming technology', 'https://bhvr.com', 'b', 'approved'),
  ('blackberry', 'BlackBerry', 'Security and IoT software', 'https://blackberry.com', 'a', 'approved'),
  ('block', 'Block', 'Financial technology', 'https://block.xyz', 'a', 'approved'),
  ('bloomberg', 'Bloomberg', 'Financial technology', 'https://www.bloomberg.com/company', 'b', 'approved'),
  ('blue-origin', 'Blue Origin', 'Space technology', 'https://www.blueorigin.com', 'b', 'approved'),
  ('bmc', 'BMC Software', 'IT operations software', 'https://www.bmc.com', 'b', 'approved'),
  ('booking', 'Booking Holdings', 'Travel technology', 'https://www.bookingholdings.com', 'a', 'approved'),
  ('boomi', 'Boomi', 'Integration software', 'https://boomi.com', 'b', 'approved'),
  ('boston-dynamics', 'Boston Dynamics', 'Robotics technology', 'https://bostondynamics.com', 'b', 'approved'),
  ('brex', 'Brex', 'Financial technology', 'https://brex.com', 'b', 'approved'),
  ('broadcom', 'Broadcom', 'Semiconductor and infrastructure software', 'https://broadcom.com', 'a', 'approved'),
  ('broadridge', 'Broadridge', 'Financial technology', 'https://www.broadridge.com', 'a', 'approved'),
  ('cadence', 'Cadence', 'Semiconductor design software', 'https://cadence.com', 'a', 'approved'),
  ('carta', 'Carta', 'Financial technology', 'https://carta.com', 'b', 'approved'),
  ('celestica', 'Celestica', 'Electronics manufacturing technology', 'https://www.celestica.com', 'a', 'approved'),
  ('cisco', 'Cisco', 'Networking technology', 'https://cisco.com', 'a', 'approved'),
  ('cloud-software-group', 'Cloud Software Group', 'Enterprise software', 'https://www.cloud.com', 'b', 'approved'),
  ('cloudera', 'Cloudera', 'Data platforms', 'https://www.cloudera.com', 'b', 'approved'),
  ('cohesity', 'Cohesity', 'Data security and management', 'https://www.cohesity.com', 'b', 'approved'),
  ('constellation-software', 'Constellation Software', 'Vertical market software', 'https://csisoftware.com', 'a', 'approved'),
  ('cornerstone', 'Cornerstone OnDemand', 'Learning technology', 'https://www.cornerstoneondemand.com', 'b', 'approved'),
  ('costar', 'CoStar Group', 'Real estate information technology', 'https://www.costargroup.com', 'a', 'approved'),
  ('coupa', 'Coupa', 'Spend management software', 'https://www.coupa.com', 'b', 'approved'),
  ('coveo', 'Coveo', 'Enterprise AI search', 'https://coveo.com', 'a', 'approved'),
  ('credit-karma', 'Credit Karma', 'Financial technology', 'https://creditkarma.com', 'a', 'approved'),
  ('crowdstrike', 'CrowdStrike', 'Security technology', 'https://crowdstrike.com', 'a', 'approved'),
  ('d2l', 'D2L', 'Learning technology', 'https://d2l.com', 'c', 'approved'),
  ('databricks', 'Databricks', 'Data infrastructure', 'https://databricks.com', 'b', 'approved'),
  ('dayforce', 'Dayforce', 'HR technology', 'https://www.dayforce.com', 'a', 'approved'),
  ('deel', 'Deel', 'HR technology', 'https://deel.com', 'b', 'approved'),
  ('dell', 'Dell', 'Computing hardware', 'https://dell.com', 'a', 'approved'),
  ('descartes', 'Descartes', 'Logistics technology', 'https://descartes.com', 'a', 'approved'),
  ('discord', 'Discord', 'Consumer technology and platforms', 'https://discord.com', 'b', 'approved'),
  ('docebo', 'Docebo', 'Learning technology', 'https://docebo.com', 'a', 'approved'),
  ('ebay', 'eBay', 'Commerce technology', 'https://ebay.com', 'a', 'approved'),
  ('ecobee', 'ecobee', 'Smart home technology', 'https://ecobee.com', 'c', 'approved'),
  ('electronic-arts', 'Electronic Arts', 'Gaming technology', 'https://ea.com', 'b', 'approved'),
  ('ellucian', 'Ellucian', 'Education technology', 'https://www.ellucian.com', 'b', 'approved'),
  ('enghouse', 'Enghouse Systems', 'Enterprise software', 'https://www.enghouse.com', 'a', 'approved'),
  ('epic-games', 'Epic Games', 'Gaming technology', 'https://epicgames.com', 'b', 'approved'),
  ('epic-systems', 'Epic Systems', 'Health technology', 'https://epic.com', 'b', 'approved'),
  ('epicor', 'Epicor', 'Enterprise software', 'https://www.epicor.com', 'b', 'approved'),
  ('esri', 'Esri', 'Geospatial software', 'https://www.esri.com', 'b', 'approved'),
  ('etsy', 'Etsy', 'Commerce technology', 'https://etsy.com', 'a', 'approved'),
  ('expedia', 'Expedia Group', 'Travel technology', 'https://expediagroup.com', 'a', 'approved'),
  ('f5', 'F5', 'Application security and delivery', 'https://f5.com', 'a', 'approved'),
  ('factset', 'FactSet', 'Financial technology', 'https://www.factset.com', 'a', 'approved'),
  ('faire', 'Faire', 'Commerce technology', 'https://faire.com', 'b', 'approved'),
  ('fico', 'FICO', 'Analytics software', 'https://www.fico.com', 'a', 'approved'),
  ('fis', 'FIS', 'Financial technology', 'https://www.fisglobal.com', 'a', 'approved'),
  ('fiserv', 'Fiserv', 'Financial technology', 'https://www.fiserv.com', 'a', 'approved'),
  ('fivetran', 'Fivetran', 'Data infrastructure', 'https://fivetran.com', 'b', 'approved'),
  ('flexport', 'Flexport', 'Logistics technology', 'https://www.flexport.com', 'b', 'approved'),
  ('fortinet', 'Fortinet', 'Security technology', 'https://fortinet.com', 'a', 'approved'),
  ('fullscript', 'Fullscript', 'Health technology', 'https://fullscript.com', 'b', 'approved'),
  ('garmin', 'Garmin', 'Consumer technology', 'https://garmin.com', 'a', 'approved'),
  ('gen-digital', 'Gen Digital', 'Security technology', 'https://gendigital.com', 'a', 'approved'),
  ('genesys', 'Genesys', 'Customer experience technology', 'https://www.genesys.com', 'b', 'approved'),
  ('genetec', 'Genetec', 'Security technology', 'https://genetec.com', 'b', 'approved'),
  ('geotab', 'Geotab', 'Telematics technology', 'https://geotab.com', 'b', 'approved'),
  ('global-payments', 'Global Payments', 'Payments technology', 'https://www.globalpayments.com', 'a', 'approved'),
  ('global-relay', 'Global Relay', 'Compliance technology', 'https://globalrelay.net', 'b', 'approved'),
  ('globalfoundries', 'GlobalFoundries', 'Semiconductor manufacturing', 'https://gf.com', 'a', 'approved'),
  ('godaddy', 'GoDaddy', 'Internet infrastructure', 'https://godaddy.com', 'a', 'approved'),
  ('gong', 'Gong', 'Revenue technology', 'https://www.gong.io', 'b', 'approved'),
  ('grafana-labs', 'Grafana Labs', 'Developer platforms', 'https://grafana.com', 'b', 'approved'),
  ('grammarly', 'Grammarly', 'Software and cloud technology', 'https://grammarly.com', 'b', 'approved'),
  ('gusto', 'Gusto', 'HR technology', 'https://gusto.com', 'b', 'approved'),
  ('hashicorp', 'HashiCorp', 'Infrastructure software', 'https://www.hashicorp.com', 'a', 'approved'),
  ('hopper', 'Hopper', 'Travel technology', 'https://hopper.com', 'b', 'approved'),
  ('hp', 'HP', 'Computing hardware', 'https://hp.com', 'a', 'approved'),
  ('hpe', 'Hewlett Packard Enterprise', 'Enterprise technology', 'https://hpe.com', 'a', 'approved'),
  ('indeed', 'Indeed', 'Employment technology', 'https://www.indeed.com', 'b', 'approved'),
  ('index-exchange', 'Index Exchange', 'Advertising technology', 'https://www.indexexchange.com', 'c', 'approved'),
  ('infor', 'Infor', 'Enterprise software', 'https://www.infor.com', 'b', 'approved'),
  ('informatica', 'Informatica', 'Data management software', 'https://www.informatica.com', 'a', 'approved'),
  ('instacart', 'Instacart', 'Local commerce technology', 'https://instacart.com', 'c', 'approved'),
  ('instructure', 'Instructure', 'Education technology', 'https://instructure.com', 'b', 'approved'),
  ('intuit', 'Intuit', 'Financial software', 'https://intuit.com', 'a', 'approved'),
  ('jack-henry', 'Jack Henry', 'Financial software', 'https://www.jackhenry.com', 'a', 'approved'),
  ('juniper', 'Juniper Networks', 'Networking technology', 'https://juniper.net', 'a', 'approved'),
  ('justworks', 'Justworks', 'HR technology', 'https://www.justworks.com', 'b', 'approved'),
  ('kaseya', 'Kaseya', 'IT management software', 'https://www.kaseya.com', 'b', 'approved'),
  ('keysight', 'Keysight', 'Electronic test technology', 'https://www.keysight.com', 'a', 'approved'),
  ('kinaxis', 'Kinaxis', 'Supply chain software', 'https://kinaxis.com', 'a', 'approved'),
  ('kla', 'KLA', 'Semiconductor equipment', 'https://kla.com', 'a', 'approved'),
  ('knowbe4', 'KnowBe4', 'Security technology', 'https://www.knowbe4.com', 'b', 'approved'),
  ('kraken', 'Kraken', 'Financial technology', 'https://kraken.com', 'b', 'approved'),
  ('lam-research', 'Lam Research', 'Semiconductor equipment', 'https://lamresearch.com', 'a', 'approved'),
  ('lightspeed', 'Lightspeed Commerce', 'Commerce technology', 'https://lightspeedhq.com', 'a', 'approved'),
  ('mailchimp', 'Mailchimp', 'Marketing technology', 'https://mailchimp.com', 'a', 'approved'),
  ('marvell', 'Marvell', 'Semiconductor technology', 'https://marvell.com', 'a', 'approved'),
  ('mastercard', 'Mastercard', 'Payments technology', 'https://mastercard.com', 'a', 'approved'),
  ('mathworks', 'MathWorks', 'Engineering software', 'https://www.mathworks.com', 'b', 'approved'),
  ('maxar', 'Maxar', 'Space technology', 'https://www.maxar.com', 'b', 'approved'),
  ('mcafee', 'McAfee', 'Security technology', 'https://www.mcafee.com', 'b', 'approved'),
  ('mda-space', 'MDA Space', 'Space technology', 'https://mda.space', 'a', 'approved'),
  ('medallia', 'Medallia', 'Experience management software', 'https://www.medallia.com', 'b', 'approved'),
  ('microchip', 'Microchip', 'Semiconductor technology', 'https://microchip.com', 'a', 'approved'),
  ('micron', 'Micron', 'Semiconductor technology', 'https://micron.com', 'a', 'approved'),
  ('miro', 'Miro', 'Collaboration software', 'https://miro.com', 'b', 'approved'),
  ('mitel', 'Mitel', 'Business communications technology', 'https://mitel.com', 'b', 'approved'),
  ('monolithic-power', 'Monolithic Power Systems', 'Semiconductor technology', 'https://www.monolithicpower.com', 'a', 'approved'),
  ('motorola-solutions', 'Motorola Solutions', 'Public safety technology', 'https://motorolasolutions.com', 'a', 'approved'),
  ('netapp', 'NetApp', 'Data storage technology', 'https://netapp.com', 'a', 'approved'),
  ('new-relic', 'New Relic', 'Observability software', 'https://newrelic.com', 'b', 'approved'),
  ('notion', 'Notion', 'Software and cloud technology', 'https://www.notion.com', 'b', 'approved'),
  ('nuvei', 'Nuvei', 'Payments technology', 'https://nuvei.com', 'b', 'approved'),
  ('nxp', 'NXP', 'Semiconductor technology', 'https://nxp.com', 'a', 'approved'),
  ('okta', 'Okta', 'Identity security', 'https://www.okta.com', 'c', 'approved'),
  ('onsemi', 'onsemi', 'Semiconductor technology', 'https://onsemi.com', 'a', 'approved'),
  ('opentext', 'OpenText', 'Enterprise information software', 'https://opentext.com', 'a', 'approved'),
  ('optimizely', 'Optimizely', 'Digital experience software', 'https://www.optimizely.com', 'b', 'approved'),
  ('pagerduty', 'PagerDuty', 'Developer platforms', 'https://pagerduty.com', 'c', 'approved'),
  ('palantir', 'Palantir', 'Data analytics software', 'https://palantir.com', 'a', 'approved'),
  ('palo-alto-networks', 'Palo Alto Networks', 'Security technology', 'https://paloaltonetworks.com', 'a', 'approved'),
  ('paychex', 'Paychex', 'HR technology', 'https://www.paychex.com', 'a', 'approved'),
  ('paycom', 'Paycom', 'Human capital software', 'https://paycom.com', 'a', 'approved'),
  ('paypal', 'PayPal', 'Financial technology', 'https://paypal.com', 'a', 'approved'),
  ('ping-identity', 'Ping Identity', 'Identity security', 'https://www.pingidentity.com', 'b', 'approved'),
  ('plaid', 'Plaid', 'Financial infrastructure', 'https://plaid.com', 'b', 'approved'),
  ('pluralsight', 'Pluralsight', 'Learning technology', 'https://www.pluralsight.com', 'b', 'approved'),
  ('pointclickcare', 'PointClickCare', 'Health technology', 'https://pointclickcare.com', 'b', 'approved'),
  ('powerschool', 'PowerSchool', 'Education technology', 'https://www.powerschool.com', 'b', 'approved'),
  ('proofpoint', 'Proofpoint', 'Security technology', 'https://www.proofpoint.com', 'b', 'approved'),
  ('ptc', 'PTC', 'Industrial software', 'https://ptc.com', 'a', 'approved'),
  ('qlik', 'Qlik', 'Analytics software', 'https://www.qlik.com', 'b', 'approved'),
  ('qorvo', 'Qorvo', 'Semiconductor technology', 'https://qorvo.com', 'a', 'approved'),
  ('qualcomm', 'Qualcomm', 'Semiconductor technology', 'https://qualcomm.com', 'a', 'approved'),
  ('qualtrics', 'Qualtrics', 'Experience management software', 'https://www.qualtrics.com', 'b', 'approved'),
  ('rakuten-kobo', 'Rakuten Kobo', 'Consumer technology', 'https://www.kobo.com', 'c', 'approved'),
  ('ramp', 'Ramp', 'Financial technology', 'https://ramp.com', 'b', 'approved'),
  ('red-hat', 'Red Hat', 'Open source software', 'https://www.redhat.com', 'a', 'approved'),
  ('riot-games', 'Riot Games', 'Gaming technology', 'https://riotgames.com', 'b', 'approved'),
  ('rippling', 'Rippling', 'HR technology', 'https://rippling.com', 'b', 'approved'),
  ('robinhood', 'Robinhood', 'Financial technology', 'https://robinhood.com', 'a', 'approved'),
  ('rockstar-games', 'Rockstar Games', 'Gaming technology', 'https://rockstargames.com', 'a', 'approved'),
  ('roper', 'Roper Technologies', 'Vertical software', 'https://www.ropertech.com', 'a', 'approved'),
  ('sap', 'SAP', 'Enterprise software', 'https://sap.com', 'c', 'approved'),
  ('sas', 'SAS', 'Analytics software', 'https://www.sas.com', 'b', 'approved'),
  ('scale-ai', 'Scale AI', 'Artificial intelligence', 'https://scale.com', 'b', 'approved'),
  ('scopely', 'Scopely', 'Gaming technology', 'https://www.scopely.com', 'b', 'approved'),
  ('seagate', 'Seagate', 'Data storage technology', 'https://seagate.com', 'a', 'approved'),
  ('seismic', 'Seismic', 'Sales enablement software', 'https://seismic.com', 'b', 'approved'),
  ('servicenow', 'ServiceNow', 'Enterprise workflow software', 'https://servicenow.com', 'a', 'approved'),
  ('skyworks', 'Skyworks Solutions', 'Semiconductor technology', 'https://skyworksinc.com', 'a', 'approved'),
  ('smartsheet', 'Smartsheet', 'Work management software', 'https://www.smartsheet.com', 'b', 'approved'),
  ('snyk', 'Snyk', 'Security technology', 'https://snyk.io', 'b', 'approved'),
  ('solarwinds', 'SolarWinds', 'IT management software', 'https://www.solarwinds.com', 'b', 'approved'),
  ('spacex', 'SpaceX', 'Space technology', 'https://spacex.com', 'b', 'approved'),
  ('splunk', 'Splunk', 'Data platforms', 'https://www.splunk.com', 'a', 'approved'),
  ('squarespace', 'Squarespace', 'Software and cloud technology', 'https://squarespace.com', 'b', 'approved'),
  ('supermicro', 'Supermicro', 'Computing hardware', 'https://supermicro.com', 'a', 'approved'),
  ('synopsys', 'Synopsys', 'Semiconductor design software', 'https://synopsys.com', 'a', 'approved'),
  ('take-two', 'Take-Two Interactive', 'Gaming technology', 'https://take2games.com', 'a', 'approved'),
  ('tanium', 'Tanium', 'Security technology', 'https://www.tanium.com', 'b', 'approved'),
  ('tenstorrent', 'Tenstorrent', 'Semiconductor technology', 'https://tenstorrent.com', 'c', 'approved'),
  ('teradyne', 'Teradyne', 'Semiconductor equipment', 'https://www.teradyne.com', 'a', 'approved'),
  ('tesla', 'Tesla', 'Electric vehicle and energy technology', 'https://tesla.com', 'a', 'approved'),
  ('texas-instruments', 'Texas Instruments', 'Semiconductor technology', 'https://ti.com', 'a', 'approved'),
  ('the-trade-desk', 'The Trade Desk', 'Advertising technology', 'https://thetradedesk.com', 'a', 'approved'),
  ('trellix', 'Trellix', 'Security technology', 'https://www.trellix.com', 'b', 'approved'),
  ('trimble', 'Trimble', 'Industrial technology', 'https://www.trimble.com', 'a', 'approved'),
  ('twitch', 'Twitch', 'Streaming technology', 'https://twitch.tv', 'a', 'approved'),
  ('tyler-technologies', 'Tyler Technologies', 'Public sector software', 'https://www.tylertech.com', 'a', 'approved'),
  ('ubisoft', 'Ubisoft', 'Gaming technology', 'https://ubisoft.com', 'c', 'approved'),
  ('ukg', 'UKG', 'HR technology', 'https://www.ukg.com', 'b', 'approved'),
  ('veeam', 'Veeam', 'Data protection software', 'https://www.veeam.com', 'b', 'approved'),
  ('veeva', 'Veeva', 'Life sciences software', 'https://veeva.com', 'a', 'approved'),
  ('verisign', 'VeriSign', 'Internet infrastructure', 'https://verisign.com', 'a', 'approved'),
  ('verkada', 'Verkada', 'Security technology', 'https://www.verkada.com', 'b', 'approved'),
  ('visa', 'Visa', 'Payments technology', 'https://visa.com', 'a', 'approved'),
  ('waymo', 'Waymo', 'Autonomous driving technology', 'https://waymo.com', 'a', 'approved'),
  ('western-digital', 'Western Digital', 'Data storage technology', 'https://www.westerndigital.com', 'a', 'approved'),
  ('wiz', 'Wiz', 'Security technology', 'https://wiz.io', 'b', 'approved'),
  ('workday', 'Workday', 'Enterprise software', 'https://workday.com', 'a', 'approved'),
  ('x', 'X', 'Consumer technology and platforms', 'https://x.com', 'b', 'approved'),
  ('xai', 'xAI', 'Artificial intelligence', 'https://x.ai', 'b', 'approved'),
  ('yahoo', 'Yahoo', 'Internet products', 'https://www.yahooinc.com', 'b', 'approved'),
  ('zebra', 'Zebra Technologies', 'Enterprise hardware', 'https://zebra.com', 'a', 'approved'),
  ('zendesk', 'Zendesk', 'Customer service software', 'https://www.zendesk.com', 'b', 'approved'),
  ('zipline', 'Zipline', 'Robotics technology', 'https://flyzipline.com', 'b', 'approved'),
  ('zoom', 'Zoom', 'Communications technology', 'https://www.zoom.com', 'a', 'approved'),
  ('zoox', 'Zoox', 'Mobility technology', 'https://zoox.com', 'a', 'approved'),
  ('zscaler', 'Zscaler', 'Security technology', 'https://zscaler.com', 'a', 'approved'),
  ('zynga', 'Zynga', 'Gaming technology', 'https://www.zynga.com', 'a', 'approved')
on conflict (key) do update set
  name = excluded.name,
  industry = excluded.industry,
  website_url = coalesce(public.companies.website_url, excluded.website_url),
  coverage_clause = excluded.coverage_clause;

insert into public.company_domains (domain, company_key, company_name, industry, status)
values
  ('activision.com', 'activision-blizzard', 'Activision Blizzard', 'Gaming technology', 'approved'),
  ('blizzard.com', 'activision-blizzard', 'Activision Blizzard', 'Gaming technology', 'approved'),
  ('adp.com', 'adp', 'ADP', 'HR technology', 'approved'),
  ('affirm.com', 'affirm', 'Affirm', 'Financial technology', 'approved'),
  ('akamai.com', 'akamai', 'Akamai', 'Internet infrastructure', 'approved'),
  ('alteryx.com', 'alteryx', 'Alteryx', 'Analytics software', 'approved'),
  ('analog.com', 'analog-devices', 'Analog Devices', 'Semiconductor technology', 'approved'),
  ('anaplan.com', 'anaplan', 'Anaplan', 'Planning software', 'approved'),
  ('anduril.com', 'anduril', 'Anduril', 'Defense technology', 'approved'),
  ('ansys.com', 'ansys', 'Ansys', 'Simulation software', 'approved'),
  ('appliedintuition.com', 'applied-intuition', 'Applied Intuition', 'Mobility technology', 'approved'),
  ('amat.com', 'applied-materials', 'Applied Materials', 'Semiconductor equipment', 'approved'),
  ('applovin.com', 'applovin', 'AppLovin', 'Mobile advertising technology', 'approved'),
  ('arcticwolf.com', 'arctic-wolf', 'Arctic Wolf', 'Security technology', 'approved'),
  ('arista.com', 'arista', 'Arista', 'Networking technology', 'approved'),
  ('assent.com', 'assent', 'Assent', 'Supply chain compliance software', 'approved'),
  ('athenahealth.com', 'athenahealth', 'athenahealth', 'Health technology', 'approved'),
  ('autodesk.com', 'autodesk', 'Autodesk', 'Design software', 'approved'),
  ('automationanywhere.com', 'automation-anywhere', 'Automation Anywhere', 'Automation software', 'approved'),
  ('automattic.com', 'automattic', 'Automattic', 'Web publishing technology', 'approved'),
  ('avalara.com', 'avalara', 'Avalara', 'Tax technology', 'approved'),
  ('axon.com', 'axon', 'Axon', 'Public safety technology', 'approved'),
  ('bamboohr.com', 'bamboohr', 'BambooHR', 'HR technology', 'approved'),
  ('barracuda.com', 'barracuda', 'Barracuda Networks', 'Security technology', 'approved'),
  ('bhvr.com', 'behaviour-interactive', 'Behaviour Interactive', 'Gaming technology', 'approved'),
  ('blackberry.com', 'blackberry', 'BlackBerry', 'Security and IoT software', 'approved'),
  ('block.xyz', 'block', 'Block', 'Financial technology', 'approved'),
  ('squareup.com', 'block', 'Block', 'Financial technology', 'approved'),
  ('bloomberg.com', 'bloomberg', 'Bloomberg', 'Financial technology', 'approved'),
  ('bloomberg.net', 'bloomberg', 'Bloomberg', 'Financial technology', 'approved'),
  ('blueorigin.com', 'blue-origin', 'Blue Origin', 'Space technology', 'approved'),
  ('bmc.com', 'bmc', 'BMC Software', 'IT operations software', 'approved'),
  ('booking.com', 'booking', 'Booking Holdings', 'Travel technology', 'approved'),
  ('bookingholdings.com', 'booking', 'Booking Holdings', 'Travel technology', 'approved'),
  ('boomi.com', 'boomi', 'Boomi', 'Integration software', 'approved'),
  ('bostondynamics.com', 'boston-dynamics', 'Boston Dynamics', 'Robotics technology', 'approved'),
  ('brex.com', 'brex', 'Brex', 'Financial technology', 'approved'),
  ('broadcom.com', 'broadcom', 'Broadcom', 'Semiconductor and infrastructure software', 'approved'),
  ('broadridge.com', 'broadridge', 'Broadridge', 'Financial technology', 'approved'),
  ('cadence.com', 'cadence', 'Cadence', 'Semiconductor design software', 'approved'),
  ('carta.com', 'carta', 'Carta', 'Financial technology', 'approved'),
  ('celestica.com', 'celestica', 'Celestica', 'Electronics manufacturing technology', 'approved'),
  ('cisco.com', 'cisco', 'Cisco', 'Networking technology', 'approved'),
  ('cloud.com', 'cloud-software-group', 'Cloud Software Group', 'Enterprise software', 'approved'),
  ('citrix.com', 'cloud-software-group', 'Cloud Software Group', 'Enterprise software', 'approved'),
  ('cloudera.com', 'cloudera', 'Cloudera', 'Data platforms', 'approved'),
  ('cohesity.com', 'cohesity', 'Cohesity', 'Data security and management', 'approved'),
  ('csisoftware.com', 'constellation-software', 'Constellation Software', 'Vertical market software', 'approved'),
  ('csod.com', 'cornerstone', 'Cornerstone OnDemand', 'Learning technology', 'approved'),
  ('cornerstoneondemand.com', 'cornerstone', 'Cornerstone OnDemand', 'Learning technology', 'approved'),
  ('costar.com', 'costar', 'CoStar Group', 'Real estate information technology', 'approved'),
  ('coupa.com', 'coupa', 'Coupa', 'Spend management software', 'approved'),
  ('coveo.com', 'coveo', 'Coveo', 'Enterprise AI search', 'approved'),
  ('creditkarma.com', 'credit-karma', 'Credit Karma', 'Financial technology', 'approved'),
  ('crowdstrike.com', 'crowdstrike', 'CrowdStrike', 'Security technology', 'approved'),
  ('d2l.com', 'd2l', 'D2L', 'Learning technology', 'approved'),
  ('databricks.com', 'databricks', 'Databricks', 'Data infrastructure', 'approved'),
  ('dayforce.com', 'dayforce', 'Dayforce', 'HR technology', 'approved'),
  ('ceridian.com', 'dayforce', 'Dayforce', 'HR technology', 'approved'),
  ('deel.com', 'deel', 'Deel', 'HR technology', 'approved'),
  ('dell.com', 'dell', 'Dell', 'Computing hardware', 'approved'),
  ('descartes.com', 'descartes', 'Descartes', 'Logistics technology', 'approved'),
  ('discord.com', 'discord', 'Discord', 'Consumer technology and platforms', 'approved'),
  ('docebo.com', 'docebo', 'Docebo', 'Learning technology', 'approved'),
  ('ebay.com', 'ebay', 'eBay', 'Commerce technology', 'approved'),
  ('ecobee.com', 'ecobee', 'ecobee', 'Smart home technology', 'approved'),
  ('ea.com', 'electronic-arts', 'Electronic Arts', 'Gaming technology', 'approved'),
  ('ellucian.com', 'ellucian', 'Ellucian', 'Education technology', 'approved'),
  ('enghouse.com', 'enghouse', 'Enghouse Systems', 'Enterprise software', 'approved'),
  ('epicgames.com', 'epic-games', 'Epic Games', 'Gaming technology', 'approved'),
  ('epic.com', 'epic-systems', 'Epic Systems', 'Health technology', 'approved'),
  ('epicor.com', 'epicor', 'Epicor', 'Enterprise software', 'approved'),
  ('esri.com', 'esri', 'Esri', 'Geospatial software', 'approved'),
  ('etsy.com', 'etsy', 'Etsy', 'Commerce technology', 'approved'),
  ('expediagroup.com', 'expedia', 'Expedia Group', 'Travel technology', 'approved'),
  ('f5.com', 'f5', 'F5', 'Application security and delivery', 'approved'),
  ('factset.com', 'factset', 'FactSet', 'Financial technology', 'approved'),
  ('faire.com', 'faire', 'Faire', 'Commerce technology', 'approved'),
  ('fico.com', 'fico', 'FICO', 'Analytics software', 'approved'),
  ('fisglobal.com', 'fis', 'FIS', 'Financial technology', 'approved'),
  ('fiserv.com', 'fiserv', 'Fiserv', 'Financial technology', 'approved'),
  ('fivetran.com', 'fivetran', 'Fivetran', 'Data infrastructure', 'approved'),
  ('flexport.com', 'flexport', 'Flexport', 'Logistics technology', 'approved'),
  ('fortinet.com', 'fortinet', 'Fortinet', 'Security technology', 'approved'),
  ('fullscript.com', 'fullscript', 'Fullscript', 'Health technology', 'approved'),
  ('garmin.com', 'garmin', 'Garmin', 'Consumer technology', 'approved'),
  ('gendigital.com', 'gen-digital', 'Gen Digital', 'Security technology', 'approved'),
  ('genesys.com', 'genesys', 'Genesys', 'Customer experience technology', 'approved'),
  ('genetec.com', 'genetec', 'Genetec', 'Security technology', 'approved'),
  ('geotab.com', 'geotab', 'Geotab', 'Telematics technology', 'approved'),
  ('globalpayments.com', 'global-payments', 'Global Payments', 'Payments technology', 'approved'),
  ('globalrelay.net', 'global-relay', 'Global Relay', 'Compliance technology', 'approved'),
  ('gf.com', 'globalfoundries', 'GlobalFoundries', 'Semiconductor manufacturing', 'approved'),
  ('godaddy.com', 'godaddy', 'GoDaddy', 'Internet infrastructure', 'approved'),
  ('gong.io', 'gong', 'Gong', 'Revenue technology', 'approved'),
  ('grafana.com', 'grafana-labs', 'Grafana Labs', 'Developer platforms', 'approved'),
  ('grammarly.com', 'grammarly', 'Grammarly', 'Software and cloud technology', 'approved'),
  ('gusto.com', 'gusto', 'Gusto', 'HR technology', 'approved'),
  ('hashicorp.com', 'hashicorp', 'HashiCorp', 'Infrastructure software', 'approved'),
  ('hopper.com', 'hopper', 'Hopper', 'Travel technology', 'approved'),
  ('hp.com', 'hp', 'HP', 'Computing hardware', 'approved'),
  ('hpe.com', 'hpe', 'Hewlett Packard Enterprise', 'Enterprise technology', 'approved'),
  ('indeed.com', 'indeed', 'Indeed', 'Employment technology', 'approved'),
  ('indexexchange.com', 'index-exchange', 'Index Exchange', 'Advertising technology', 'approved'),
  ('infor.com', 'infor', 'Infor', 'Enterprise software', 'approved'),
  ('informatica.com', 'informatica', 'Informatica', 'Data management software', 'approved'),
  ('instacart.com', 'instacart', 'Instacart', 'Local commerce technology', 'approved'),
  ('instructure.com', 'instructure', 'Instructure', 'Education technology', 'approved'),
  ('intuit.com', 'intuit', 'Intuit', 'Financial software', 'approved'),
  ('jackhenry.com', 'jack-henry', 'Jack Henry', 'Financial software', 'approved'),
  ('juniper.net', 'juniper', 'Juniper Networks', 'Networking technology', 'approved'),
  ('justworks.com', 'justworks', 'Justworks', 'HR technology', 'approved'),
  ('kaseya.com', 'kaseya', 'Kaseya', 'IT management software', 'approved'),
  ('keysight.com', 'keysight', 'Keysight', 'Electronic test technology', 'approved'),
  ('kinaxis.com', 'kinaxis', 'Kinaxis', 'Supply chain software', 'approved'),
  ('kla.com', 'kla', 'KLA', 'Semiconductor equipment', 'approved'),
  ('knowbe4.com', 'knowbe4', 'KnowBe4', 'Security technology', 'approved'),
  ('kraken.com', 'kraken', 'Kraken', 'Financial technology', 'approved'),
  ('lamresearch.com', 'lam-research', 'Lam Research', 'Semiconductor equipment', 'approved'),
  ('lightspeedhq.com', 'lightspeed', 'Lightspeed Commerce', 'Commerce technology', 'approved'),
  ('mailchimp.com', 'mailchimp', 'Mailchimp', 'Marketing technology', 'approved'),
  ('marvell.com', 'marvell', 'Marvell', 'Semiconductor technology', 'approved'),
  ('mastercard.com', 'mastercard', 'Mastercard', 'Payments technology', 'approved'),
  ('mathworks.com', 'mathworks', 'MathWorks', 'Engineering software', 'approved'),
  ('maxar.com', 'maxar', 'Maxar', 'Space technology', 'approved'),
  ('mcafee.com', 'mcafee', 'McAfee', 'Security technology', 'approved'),
  ('mda.space', 'mda-space', 'MDA Space', 'Space technology', 'approved'),
  ('medallia.com', 'medallia', 'Medallia', 'Experience management software', 'approved'),
  ('microchip.com', 'microchip', 'Microchip', 'Semiconductor technology', 'approved'),
  ('micron.com', 'micron', 'Micron', 'Semiconductor technology', 'approved'),
  ('miro.com', 'miro', 'Miro', 'Collaboration software', 'approved'),
  ('mitel.com', 'mitel', 'Mitel', 'Business communications technology', 'approved'),
  ('monolithicpower.com', 'monolithic-power', 'Monolithic Power Systems', 'Semiconductor technology', 'approved'),
  ('motorolasolutions.com', 'motorola-solutions', 'Motorola Solutions', 'Public safety technology', 'approved'),
  ('netapp.com', 'netapp', 'NetApp', 'Data storage technology', 'approved'),
  ('newrelic.com', 'new-relic', 'New Relic', 'Observability software', 'approved'),
  ('makenotion.com', 'notion', 'Notion', 'Software and cloud technology', 'approved'),
  ('nuvei.com', 'nuvei', 'Nuvei', 'Payments technology', 'approved'),
  ('nxp.com', 'nxp', 'NXP', 'Semiconductor technology', 'approved'),
  ('okta.com', 'okta', 'Okta', 'Identity security', 'approved'),
  ('onsemi.com', 'onsemi', 'onsemi', 'Semiconductor technology', 'approved'),
  ('opentext.com', 'opentext', 'OpenText', 'Enterprise information software', 'approved'),
  ('optimizely.com', 'optimizely', 'Optimizely', 'Digital experience software', 'approved'),
  ('pagerduty.com', 'pagerduty', 'PagerDuty', 'Developer platforms', 'approved'),
  ('palantir.com', 'palantir', 'Palantir', 'Data analytics software', 'approved'),
  ('paloaltonetworks.com', 'palo-alto-networks', 'Palo Alto Networks', 'Security technology', 'approved'),
  ('paychex.com', 'paychex', 'Paychex', 'HR technology', 'approved'),
  ('paycom.com', 'paycom', 'Paycom', 'Human capital software', 'approved'),
  ('paypal.com', 'paypal', 'PayPal', 'Financial technology', 'approved'),
  ('pingidentity.com', 'ping-identity', 'Ping Identity', 'Identity security', 'approved'),
  ('plaid.com', 'plaid', 'Plaid', 'Financial infrastructure', 'approved'),
  ('pluralsight.com', 'pluralsight', 'Pluralsight', 'Learning technology', 'approved'),
  ('pointclickcare.com', 'pointclickcare', 'PointClickCare', 'Health technology', 'approved'),
  ('powerschool.com', 'powerschool', 'PowerSchool', 'Education technology', 'approved'),
  ('proofpoint.com', 'proofpoint', 'Proofpoint', 'Security technology', 'approved'),
  ('ptc.com', 'ptc', 'PTC', 'Industrial software', 'approved'),
  ('qlik.com', 'qlik', 'Qlik', 'Analytics software', 'approved'),
  ('qorvo.com', 'qorvo', 'Qorvo', 'Semiconductor technology', 'approved'),
  ('qualcomm.com', 'qualcomm', 'Qualcomm', 'Semiconductor technology', 'approved'),
  ('qualtrics.com', 'qualtrics', 'Qualtrics', 'Experience management software', 'approved'),
  ('kobo.com', 'rakuten-kobo', 'Rakuten Kobo', 'Consumer technology', 'approved'),
  ('ramp.com', 'ramp', 'Ramp', 'Financial technology', 'approved'),
  ('redhat.com', 'red-hat', 'Red Hat', 'Open source software', 'approved'),
  ('riotgames.com', 'riot-games', 'Riot Games', 'Gaming technology', 'approved'),
  ('rippling.com', 'rippling', 'Rippling', 'HR technology', 'approved'),
  ('robinhood.com', 'robinhood', 'Robinhood', 'Financial technology', 'approved'),
  ('rockstargames.com', 'rockstar-games', 'Rockstar Games', 'Gaming technology', 'approved'),
  ('ropertech.com', 'roper', 'Roper Technologies', 'Vertical software', 'approved'),
  ('sap.com', 'sap', 'SAP', 'Enterprise software', 'approved'),
  ('sas.com', 'sas', 'SAS', 'Analytics software', 'approved'),
  ('scale.com', 'scale-ai', 'Scale AI', 'Artificial intelligence', 'approved'),
  ('scopely.com', 'scopely', 'Scopely', 'Gaming technology', 'approved'),
  ('seagate.com', 'seagate', 'Seagate', 'Data storage technology', 'approved'),
  ('seismic.com', 'seismic', 'Seismic', 'Sales enablement software', 'approved'),
  ('servicenow.com', 'servicenow', 'ServiceNow', 'Enterprise workflow software', 'approved'),
  ('skyworksinc.com', 'skyworks', 'Skyworks Solutions', 'Semiconductor technology', 'approved'),
  ('smartsheet.com', 'smartsheet', 'Smartsheet', 'Work management software', 'approved'),
  ('snyk.io', 'snyk', 'Snyk', 'Security technology', 'approved'),
  ('solarwinds.com', 'solarwinds', 'SolarWinds', 'IT management software', 'approved'),
  ('spacex.com', 'spacex', 'SpaceX', 'Space technology', 'approved'),
  ('splunk.com', 'splunk', 'Splunk', 'Data platforms', 'approved'),
  ('squarespace.com', 'squarespace', 'Squarespace', 'Software and cloud technology', 'approved'),
  ('supermicro.com', 'supermicro', 'Supermicro', 'Computing hardware', 'approved'),
  ('synopsys.com', 'synopsys', 'Synopsys', 'Semiconductor design software', 'approved'),
  ('take2games.com', 'take-two', 'Take-Two Interactive', 'Gaming technology', 'approved'),
  ('tanium.com', 'tanium', 'Tanium', 'Security technology', 'approved'),
  ('tenstorrent.com', 'tenstorrent', 'Tenstorrent', 'Semiconductor technology', 'approved'),
  ('teradyne.com', 'teradyne', 'Teradyne', 'Semiconductor equipment', 'approved'),
  ('tesla.com', 'tesla', 'Tesla', 'Electric vehicle and energy technology', 'approved'),
  ('ti.com', 'texas-instruments', 'Texas Instruments', 'Semiconductor technology', 'approved'),
  ('thetradedesk.com', 'the-trade-desk', 'The Trade Desk', 'Advertising technology', 'approved'),
  ('trellix.com', 'trellix', 'Trellix', 'Security technology', 'approved'),
  ('trimble.com', 'trimble', 'Trimble', 'Industrial technology', 'approved'),
  ('twitch.tv', 'twitch', 'Twitch', 'Streaming technology', 'approved'),
  ('tylertech.com', 'tyler-technologies', 'Tyler Technologies', 'Public sector software', 'approved'),
  ('ubisoft.com', 'ubisoft', 'Ubisoft', 'Gaming technology', 'approved'),
  ('ukg.com', 'ukg', 'UKG', 'HR technology', 'approved'),
  ('veeam.com', 'veeam', 'Veeam', 'Data protection software', 'approved'),
  ('veeva.com', 'veeva', 'Veeva', 'Life sciences software', 'approved'),
  ('verisign.com', 'verisign', 'VeriSign', 'Internet infrastructure', 'approved'),
  ('verkada.com', 'verkada', 'Verkada', 'Security technology', 'approved'),
  ('visa.com', 'visa', 'Visa', 'Payments technology', 'approved'),
  ('waymo.com', 'waymo', 'Waymo', 'Autonomous driving technology', 'approved'),
  ('wdc.com', 'western-digital', 'Western Digital', 'Data storage technology', 'approved'),
  ('wiz.io', 'wiz', 'Wiz', 'Security technology', 'approved'),
  ('workday.com', 'workday', 'Workday', 'Enterprise software', 'approved'),
  ('x.com', 'x', 'X', 'Consumer technology and platforms', 'approved'),
  ('x.ai', 'xai', 'xAI', 'Artificial intelligence', 'approved'),
  ('yahooinc.com', 'yahoo', 'Yahoo', 'Internet products', 'approved'),
  ('zebra.com', 'zebra', 'Zebra Technologies', 'Enterprise hardware', 'approved'),
  ('zendesk.com', 'zendesk', 'Zendesk', 'Customer service software', 'approved'),
  ('flyzipline.com', 'zipline', 'Zipline', 'Robotics technology', 'approved'),
  ('zoom.us', 'zoom', 'Zoom', 'Communications technology', 'approved'),
  ('zoox.com', 'zoox', 'Zoox', 'Mobility technology', 'approved'),
  ('zscaler.com', 'zscaler', 'Zscaler', 'Security technology', 'approved'),
  ('zynga.com', 'zynga', 'Zynga', 'Gaming technology', 'approved')
on conflict (domain) do update set company_key = excluded.company_key;
